./" scomm
.TH scomm 3 "2021" "scomm"

.SH NAME
	scomm
.SH DESCRIPTION
	scomm is the swall command line. Also see swall.
.SH COMMANDS
	- exit to exit.

	- clsme to clear your page.

	- echomod turns echomod on and of. echomod prints a message in stead of a command.

	- clear and clsme will work the same in echomod and normall mode.
